version: "3"

includes:
  python:
    taskfile: ./python/Taskfile.yml
    dir: .
    flatten: true
  docker:
    taskfile: ./docker/Taskfile.yml
    dir: .
    flatten: true

tasks:
  default:
    cmds:
      - task: help

  help:
    desc: show help message
    cmds:
      - task --list-all

  info:
    desc: show directories variables defined in Taskfile
    silent: true
    cmds:
      - echo "Root Taskfile dir = {{.ROOT_DIR}}"
      - echo "Taskfile containing 'info' command = {{.TASKFILE_DIR}}"
      - echo "Current working dir = {{.USER_WORKING_DIR}}"
