version: "3"

includes:
  setup:
    taskfile: ./setup.yml
    dir: .
    flatten: true
  checks:
    taskfile: ./checks.yml
    dir: .
    flatten: true
  django:
    taskfile: ./django.yml
    dir: .
    flatten: true
